apiVersion: apps/v1
kind: Deployment
metadata:
  name: modulo-a-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: modulo-a
  template:
    metadata:
      labels:
        app: modulo-a
    spec:
      containers:
      - name: modulo-a
        image: modulo-a:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 50051
        env:
        - name: ATRASO_MS
          value: "200"       
        - name: CARGA_CPU
          value: "100000"
  

