apiVersion: apps/v1
kind: Deployment
metadata:
  name: modulo-b-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: modulo-b
  template:
    metadata:
      labels:
        app: modulo-b
    spec:
      containers:
      - name: modulo-b
        image: modulo-b:latest
        imagePullPolicy: Never # Importante para o Minikube usar a imagem local
        ports:
        - containerPort: 50052
        env:
        - name: ATRASO_MS
          value: "300"       # Atraso configurável
        - name: CARGA_CPU
          value: "500000"    # Carga de CPU configurável